export default {
    name: 'Русский',
    translation: {
        search: "Поиск",
        groups: "Группы",
        EnterSearch: "Введите поисковый запрос...",
        Film: 'Фильмы',
        Book: 'Книги',
        Game: 'Игры',
        Any: 'Любое',
        Filter: 'Фильтр по тэгам',
        Add: 'Добавить',
        Select: "Выбери...",
        Home: 'Главная',
        NoPosts: 'Нет доступных постов',
        Delete: 'Удалить',
        ReadMore: 'Читать',
        Edit: 'Редактировать',
        WelcomeBP: 'Добро Пожаловать!',
        Send: 'Отправить',
        Hello: 'Привет',
        CreateP: 'Создать Пост',
        OpenA: 'Открыть Панель Администратора',
        CreateR: 'Создать Новый Пост!',
        Title: 'Заголовок',
        TitlePl: 'Заголовк поста',
        InputReq: "Это обязательное поле.",
        InputCant: 'Поле не должно содержать более',
        characters: 'символов',
        Annotation: 'Заголовок',
        AnnotationPl: 'В этом посте я хочу рассказать о...',
        Text: 'Текст',
        TextPl: 'Вы можете использовать Markdown-разметку',
        InputTags: 'Введите Тэги',
        PreviewImage:'Картинка',
        FileSelected: 'Выбранный файл',
        SelectFile: 'Перетащите сюда файл или нажмите, чтобы выбрать файл.',
        CancelChanges: 'Отменить Изменения',
        EditPost: 'Отредактируйте Ваш Пост',
        AllUsers: 'Все пользователи',
        Username: 'Имя юзера',
        Email: 'Email',
        Admin: 'Админ',
        CreatedAt: 'Создан',
        Profile: 'Профиль',
    }
}