export default {
    name: "English",
    translation: {
        search: "Search",
        groups: "Groups",
        EnterSearch: "Enter search term...",
        Film: 'Films',
        Book: 'Books',
        Game: 'Games',
        Any: 'Any',
        Filter: 'Filter by tags',
        Add: 'Add',
        Select: "Select...",
        Home: 'Home',
        NoPosts: 'No Posts Available',
        Delete: 'Delete',
        ReadMore: 'Read more →',
        Edit: 'Edit',
        WelcomeBP: 'Welcome To Blog Post!',
        Send: 'Send',
        Hello: 'Hello',
        CreateP: 'Create Post',
        OpenA: 'Open Admin Panel',
        CreateR: 'Create New Post!',
        Title: 'Title',
        TitlePl: 'The title of the post',
        InputReq: "This input is required.",
        InputCant: 'This input can`t exceed',
        characters: 'characters',
        Annotation: 'Annotation',
        AnnotationPl: 'At this post I wanna tell about...',
        Text: 'Text',
        TextPl: 'You can use Markdown',
        InputTags: 'Input Tags',
        PreviewImage:'Preview Image',
        FileSelected: 'Select File',
        SelectFile: 'Drag and drop a file here or click to select a file.',
        CancelChanges: 'Cancel Changes',
        EditPost: 'Edit Your Post',
        AllUsers: 'All Users',
        Username: 'Username',
        Email: 'Email',
        Admin: 'Admin',
        CreatedAt: 'Created At',
        Profile: 'Profile',
    }
}